// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Q4nvuQ-43NvV0jiPy5Xrb5EmBFTDtIs',
    appId: '1:594711556348:web:dde0ac7c3ae713cb12e779',
    messagingSenderId: '594711556348',
    projectId: 'logosmart-413e2',
    authDomain: 'logosmart-413e2.firebaseapp.com',
    storageBucket: 'logosmart-413e2.firebasestorage.app',
    measurementId: 'G-QWRZ6B89Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5f4vxUgz5bVBFAJwodUMIZHM3Nq-4DrA',
    appId: '1:594711556348:android:729a0e8c7ae4ff3612e779',
    messagingSenderId: '594711556348',
    projectId: 'logosmart-413e2',
    storageBucket: 'logosmart-413e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPLdCtyvMoSzWMbRm4tYwrOTOeydXuCEc',
    appId: '1:594711556348:ios:4fb7647d957b876012e779',
    messagingSenderId: '594711556348',
    projectId: 'logosmart-413e2',
    storageBucket: 'logosmart-413e2.firebasestorage.app',
    iosBundleId: 'uz.logosmart.logosmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPLdCtyvMoSzWMbRm4tYwrOTOeydXuCEc',
    appId: '1:594711556348:ios:4fb7647d957b876012e779',
    messagingSenderId: '594711556348',
    projectId: 'logosmart-413e2',
    storageBucket: 'logosmart-413e2.firebasestorage.app',
    iosBundleId: 'uz.logosmart.logosmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Q4nvuQ-43NvV0jiPy5Xrb5EmBFTDtIs',
    appId: '1:594711556348:web:44bdb712cf4a705312e779',
    messagingSenderId: '594711556348',
    projectId: 'logosmart-413e2',
    authDomain: 'logosmart-413e2.firebaseapp.com',
    storageBucket: 'logosmart-413e2.firebasestorage.app',
    measurementId: 'G-XFTHGDVBJ6',
  );
}
